### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by picrap** [hyn/lets-encrypt#5]
Hi,

I am quite new to let's encrypt; do you have any documentation regarding your project?

Thanks.

**Comment by luceos** [comment]
My apologies for the late reply @picrap ; Let's Encrypt information can be found on [their website](https://letsencrypt.org/); they provide easy python based installers for installing free SSL certificates. My project does not rely on any other language than PHP and is meant as a generic wrapper.

Development seems a bit stale here on Github, but that's mainly due to being implemented into my Laravel multi tenancy installation for testing.

**Comment by picrap** [comment]
I know the original project, I was asking about what your project does, and how to use it. Is it supposed to replace the acme callback?

**Comment by luceos** [comment]
It calls the ACME server and allows solving the challenges returned by Let's Encrypt, after which the certificate can be immediately used.

In fact, I'm close to have it automate the whole process via PHP and writing a file in docroot on one project and set a dns record on another.

If you want to discuss this project further you can find me on [gitter](https://gitter.im/luceos) most of the time.

**Comment by picrap** [comment]
This looks good :smile:

**Comment by luceos** [comment]
I know ;) If you're able to test it out on your project in development, that would be great. I think it's really close to being production ready.

**Comment by picrap** [comment]
If it is working (or supposed to), I can test it. However, I still need a little help to get started. After installing, what am I supposed to do to start the certificate process?

**Comment by luceos** [comment]
Call all functionality manually. If you're not up to that level, await the documentation which will follow the release.

**Comment by picrap** [comment]
To me, a good integration would encapsulate all plumbing: make certificates creation and renew requests, so the only job required from the developpers would be:
- Install your library
- Setup the web server to support https

**Comment by luceos** [comment]
This is a generic wrapper. The implementation of a solver (write file to docroot, set dns record etc) would be up to the developer. I do include some basic solvers to give a hint into the right direction. But an actual implementation is based on so many factors it's hard to support all of them in a generic wrapper.

I wouldn't be surprised if more specific implementation will follow though.

**Comment by luceos** [comment]
@picrap Just to let you know, the terminal command tool will help you with what you asked for. I'll try to complete that these coming days.

**Comment by luceos** [comment]
Tagged version 0.1.1 which has a global composer command. Please check the readme.

If you have more specific questions, please create a new issue.
